database_url = "postgres://recueil:recueil@localhost:5432/recueil"
worker_url = "127.0.0.1"
worker_service_secret = "none"
cloudflare_account_id = "todo"
cloudflare_d1_database_id = "todo"
# this is for local dev only so we don't care that it's exposed
pairing_token_key = "tjIb2S5xDH0OxKqg3TJvcoqZqjVcqGrSzHXioqsm57I="
cloudflare_api_token = "todo"
archive_dir = "tmp"
r2_account_id = "todo"
r2_bucket_name = "todo"
r2_access_key_id = "todo"
r2_access_key_secret = "todo"
sidecar_url = "http://127.0.0.1:9222"
sidecar_render_host = "host.docker.internal"
ai_base_url = "https://openrouter.ai/api/v1"
ai_api_key = "todo"
ai_model = "openai/gpt-oss-20b:free"
