---
name: CI
on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    services:
      postgres:
        image: postgres:18-alpine
        env:
          POSTGRES_DB: recueil
          POSTGRES_USER: recueil
          POSTGRES_PASSWORD: recueil
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5
        ports:
          - "5432:5432"
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          cache: true
          go-version-file: go.mod
      - uses: pnpm/action-setup@v6
        with:
          version: latest
      - uses: actions/setup-node@v6
        with:
          cache: pnpm
          node-version: lts/*
      - uses: sqlc-dev/setup-sqlc@v5
        with:
          sqlc-version: 1.31.1
      - uses: opentofu/setup-opentofu@v2
        with:
          tofu_wrapper: false
      - run: tofu fmt -check -recursive
      - run: pnpm run check
      - run: pnpm run types
      - run: pnpm run lint
      - run: go mod download
      - run: "[[ -z $(go fmt ./...) ]]"
      - run: make
      - run: go test -race -v ./...
      - run: go vet ./...
      - run: pnpm run test
