---
name: CI
on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          cache: true
          go-version-file: go.mod
      - uses: pnpm/action-setup@v6
        with:
          version: latest
      - uses: actions/setup-node@v6
        with:
          cache: pnpm
          node-version: lts/*
      - uses: opentofu/setup-opentofu@v2
        with:
          tofu_wrapper: false
      - run: tofu fmt -check -recursive
      - run: pnpm run check
      - run: pnpm run types
      - run: pnpm run lint
      - run: go mod download
      - run: "[[ -z $(go fmt ./...) ]]"
      - run: make
      - run: go test -v ./...
      - run: go vet ./...
      - run: pnpm run test
